dist: bionic

language: go

go:
  - 1.x

env:
  - GO111MODULE=on

script:
  - go env
  - make build

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - npm install -g snyk && snyk test

git:
  depth: 1

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
